controllers:
    resource: ../src/Controller/
    type: attribute

app_not_found:
    path: /404
    controller: App\Controller\NotFoundController::notFound

app_stimulus:
    path: /stim
    controller: App\Controller\StimulusLController::stimulus

app_genimage:
    path: /
    controller: App\Controller\StimulusLController::stimulus

app_test:
    path: /test
    controller: App\Controller\TestController::login

# SignUpController
app_signup:
    path: /signup
    controller: App\Controller\SignUpController::signup

app_login:
    path: /login
    controller: App\Controller\SignUpController::login

app_nopass:
    path: /nopass
    controller: App\Controller\SignUpController::nopass
    
app_newpass:
    path: /newpass
    controller: App\Controller\SignUpController::newpass

app_collection:
    path: /collection
    controller: App\Controller\CollectionController::show

app_admin:
    path: /admin
    controller: App\Controller\AdminController::admin
